global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus
    honor_labels: true

    eureka_sd_configs:
      - server: http://eureka-service:8761/eureka
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        regex: config-service
        action: drop
      # App 이름을 label로 부여
      - source_labels: [__meta_eureka_app_name]
        target_label: application


      # Eureka 메타데이터에서 management.port를 가져와 주소 완성
      - source_labels: [__meta_eureka_app_instance_hostname, __meta_eureka_app_instance_metadata_management_port]
        separator: ":"
        regex: (.+):(.+)
        replacement: "$1:$2"
        target_label: __address__

      # management.port 없는 경우 드랍
      - source_labels: [__meta_eureka_app_instance_metadata_management_port]
        regex: ""
        action: drop



