server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hanium2025/msa-config-repo.git
          default-label: main
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
          clone-on-start: true
          timeout: 5

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    enabled: ${EUREKA_ENABLED:true}  # 기본값 true (즉, 환경변수로 false 설정 시 끔)
    service-url:
      defaultZone: http://discovery-service.hanium.local:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always