
server:
  port: 8000

app:
  server:
    type: APIGATEWAY-SERVER
    id: apigateway-server-1

spring:
  application:
    name: apigateway-service

grpc:
  client:
    user-service:
      address: "discovery:///user-service"  # Eureka 연동
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 10485760
      defaultLoadBalancingPolicy: round_robin  # gRPC 로드밸런싱 적용
    product-service:
      address: "discovery:///product-service"  # Eureka 연동
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 10485760
      defaultLoadBalancingPolicy: round_robin  # gRPC 로드밸런싱 적용
    notification-service:
      address: "discovery:///notification-service"  # Eureka 연동
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 10485760
      defaultLoadBalancingPolicy: round_robin  # gRPC 로드밸런싱 적용
    community-service:
      address: "discovery:///community-service"  # Eureka 연동
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 10485760
      defaultLoadBalancingPolicy: round_robin  # gRPC 로드밸런싱 적용

    community-service-2:
      address: "discovery:///community-service-2"  # Eureka 연동
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      maxInboundMessageSize: 10485760
      defaultLoadBalancingPolicy: round_robin  # gRPC 로드밸런싱 적용
      negotiationType: plaintext

jwt:
  secret: 54316f0835025f9ffb7ba988ef03b876f12d4532d770a2f83c590079f8c06d1f8cc229ffb45824d3ff2354a0ca2c2bb966e84198c8e6209e7b559f86f1391cb4
  expiration: 300

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    hanium.apigateway_service.grpc.CommunityGrpcClient: DEBUG
#    root: INFO
#    org.springframework.cloud.client.discovery: DEBUG
#    org.springframework.web: DEBUG